sudo: required
services:
  - docker

before_install:
  - docker build -t cartron/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true cartron/react-test npm test

after_success:
  - docker build -t cartron/multi-client ./client
  - docker build -t cartron/multi-nginx ./nginx
  - docker build -t cartron/multi-server ./server
  - docker build -t cartron/multi-worker ./worker

  # Login to the Docker CLI
  - docker login --username "$DOCKER_ID"  --password "$DOCKER_PASSWORD"


  # Push images to Docker Hub
  - docker push cartron/multi-client
  - docker push cartron/multi-nginx
  - docker push cartron/multi-server
  - docker push cartron/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-244142604025"
  bucket_path: "docker-multi"
  access_key_id:
      secure: "BQsryTnldgMdS77m0/08NZPCXCwa0YagqOQ6qD26aq1NUG4WEdtRH17ZgGYh1JW3BJNrM/GQxCXW29P+iaIu0T8QP45kARAACCFNfnA64ETx2DfyydfDnghy0cHvyV93CPvcX9vmHokOnQQvEpdlcd1CmiKdLq8+poBe3M70exgLr+FLrruLPlMzi6M5KqH9JpJLqfZ1j7XUIyq+eXwCh3FqX2d35G8qRJxARbeBEu457ZLfZeWbfmnHT/dZiCQnTIUxlQgGfFoMv+Hb80szR7/lH448mXKenCSqTStGexh4Up+g4bHO1yAP3IpbDKh33j/WILmMJSdYgD4coDAms7RxSPTubrFyhRaXwvfs7JBYanFypsX+ft2gBS4+Oqo2st6+WnR6ofbejzZ4UIADyd1sAVPbZjj/sCT05MJq6M/xnrQmAYW9JQ4r4HDxnyVcBXByPnNyeZz5SIidMq0sOSgwfwq+kK/uebbQSqa12TSPG6h+L+ZkwXLI+2g0qOyOvo/HkgiTGwdRGYshlcbSu9rldRIGj+g57oU4G31aqGPd/jBdXFhuZ5agsSmsIadodm0pUGWl2Z7rC3DYk+ECYjwVX4zX90k4jdyVB5Mj1F0JXLZiuWYfXy+wGX+nbkmTG94TrzlbMsb4mPyfDTV8sc5CKmRs25Pp+XPrm9i+ku8="
  secret_access_key:
      secure: "E4Ttekjm9Cnk1H36DP113aylmR2LGPTwPmW44U4+pObpub8qTsCL0jb9UtWM5vobo4mVk6zgciYK1Pkt7bETqOWO08jEny4gndnOUvAIpXvOFUBcC0s3km2mI+G+Oja+bEZSNrkZ2t3AJbDsu1lYdcb7iWLy1Ay6Uw52W7gfa3nTxM71rN7/X8/PChGDgFpmi9LeRKfxH9xjdBoUVMH10PphvDxazL+bGXWAylAD3ohRKB4aBxKYVcRUzNKTAf//SgsU9a0G1IewmqFGLzx5QH6VEAL9wGp1ktrCGSvQKjaWjiM1SsU0xg8u/oqFiFdiPTNnl0N70o/wRveNS93kTgt0EAcbTjU4tMSIorEQmtLKWqk02su9FQC0+VT/9Qw4C3EU6vm6jtAff+rC+Qq/mlIwptZxgapMJ7Z2uTaQXTezfNP9VA+PLmsYG7rLZtMXzs9nJWkz9FWtzS+Zqt/+BrE13QYXmWoyfKfGxRC3O72de5mEFgXOZA+fg+x4L994xG/4RF/kBGgWNqX+M/XgAZb7wqalWCxBW8GKBYYgG1iKmdEpxcf9+Iq6Ccfk8RPia7pTySEMTiFS7sHv2I8dtFGlMW3DgTHS7FB57eHF6dlPhVwAafqKksPYcoe6bxzfEpSWjma24zSmyJakRJNqlF/cqHA/GnuKJZFsFORJS7Q="
  on:
    branch: master
