sudo: required
services:
  - docker

before_install:
  - docker build -t cartron/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true cartron/react-test npm test

after_success:
  - docker build -t cartron/multi-client ./client
  - docker build -t cartron/multi-nginx ./nginx
  - docker build -t cartron/multi-server ./server
  - docker build -t cartron/multi-worker ./worker

  # Login to the Docker CLI
  - docker login --username "$DOCKER_ID"  --password "$DOCKER_PASSWORD"


  # Push images to Docker Hub
  - docker push cartron/multi-client
  - docker push cartron/multi-nginx
  - docker push cartron/multi-server
  - docker push cartron/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-244142604025
  bucket_path: docker-multi
  access_key_id:
    secure: "TuoOy5Dr776NleFlHbHbprtpe7PdnnHH9xatvnlXomKG1HUcN+TVaxiw/5VjKuTszYd0lRq/txAFk7tLrhwCaig5/Rjm/VNqOSMDvtjQ+0fyu1xljR/+Fi6aODDeBqvT6iCKb3xeP4BoLNFdv7ko/XJwJOXpPZSj1Ez8kWoOBy/5izL1av/O06XAcWTZxaVReEqzrd6zK0Jj04L4HuoEau44Qcw5HhEYw9QSjI+rdmes/NqfQAJwJl6dUxE1rIFoBqa5BcmfN3i0SMx8wpp+esg5JArHrTwQgX8jIDy+zNMr/8wUcb7RlMcXri5q1sa25Hi+UwN4UNA58ZaCZi1pH7zQ3tSVh0fNIWX1VII/gOw38d3R47t720i00+wrvVRKqmPsXs4ybYN9lnnZq0NYFyy0z1m+hDCkY4PoAPnZ+FIWE9jUxTu1YwAIhYqioEvqe+8mS5MpCFV3If4WnlMZTK3dGPN415ZdEUBMMwG0ZYq4tVjBqBu7KRRyjKLxRNsEi+Ij2znj8T48Rmx7Y7kxo52nLeEahTJah/AyknwrnXESBnXI6YIUQ8ui/wDlu5wV8nqzUeTTwewMfkWqC7NExwQPzCiyiCqrIuUy3GRa3/uD4Rl0PlFqLSeAyr2JtjDeK9zcy4GJBV6WaFkBXV7PMLv7R1NyXatOiL8NR7wR7HQ="
  secret_access_key:
    secure: "EEuuvqffPunq1wc/05vA6Q1FxS+rb0GkyCnReRpUweVGxBFyZQn5XumAGJxOHHbKt9WlXN1NzXwlWLUT4vQbB0Hgpo1YZDFGwrz+TOIcjf9RvykkBqyC6ieyvVvNF+0TQf1jKFBxDFbJpqRR7yGGYYFG6emgnvcunVyIDxD0VlrIJmBCd60p1mYpsRHKfmni2g36Ngl0oag0LxgOqlLJNd7t+4TMZ/S/jKtjetInLXBQzb26nYi+2wF/Aq7gdE66WFC7BAI9yoNgFaZBTYMF3LMbBLfSHW9v9k9GNXL1uU+MLFQSITUITRk/ziTP67YnMB0TZsmAmFZ4D17YhU3XeHWP+X2GHOj9+Wh4zLs2nwdu9F5iRPkZs2q/svzSPXIqst/loLyw6JjEToklraAJ3GFL1ij4LIVu4SyOLH8wY56cu0YN7sEjDgWk481rzhMb9/hnWtM3T2vtU6cUN2TXQUHhWpyleoUEMcKs4ukiiBGzUQFQ0tq3H2Sp+fX3uo/38O8s28eXByk57Y8vMp8Ic8yQTFTGl7sD+Mi0XgeUD0YeVu/COiG/iHAoMKOBMgdTIspiX9ubzpFSglr0A2C4cyIsrnesWS4gs59ft5/QmymQpGwfkbuqI7n87Uh9RjtojhHYA1ipgDA7Z6slHSFZBs7I8Qd2grt/7uevSbtXAZ4="
  on:
    branch: master
